markdown:     kramdown
permalink:     '/blog/:year/:title/'

pygments:     true
comments: 	  true
paginate:     5
paginate_path: '/blog/page:num/'


# Setup
title:            Brandon Hubbard
tagline:          'WordPress Developer'
description:      'Personal Website for Brandon Hubbard.'
url:              http://www.brandonhubbard.com

author:
  name:           'Brandon Hubbard'
  url:            https://twitter.com/bhubbard